steps:
  # Step 1: Install dependencies & build Next.js
  - name: "node:20"
    entrypoint: npm
    args: ["install"]

  - name: "node:20"
    entrypoint: npm
    args: ["run", "build"]

  # Step 1: Build the image using Buildpacks
  - name: gcr.io/buildpacks/builder
    args:
      - build
      - asia-south1-docker.pkg.dev/iron-portfolio-470506-p3/campaign-app-repo/campaign-hive:$COMMIT_SHA
      - --builder=gcr.io/buildpacks/builder:v1

  # Step 2: Deploy to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - campaign-hive
      - --image=asia-south1-docker.pkg.dev/iron-portfolio-470506-p3/campaign-app-repo/campaign-hive:$COMMIT_SHA
      - --region=asia-south1
      - --platform=managed
      - --allow-unauthenticated

images:
  - "asia-south1-docker.pkg.dev/iron-portfolio-470506-p3/campaign-app-repo/campaign-hive:$COMMIT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY
